In [137]:
#PART 1
import numpy as np



A = np.random.randint(1, 100, (10, 10))

n = A[0::2]
y = A[:, 1::2]

#part a)
B = A.min()
C = A.max()

#part b)
Average = n.mean(axis=1)

#part c)
std = y.std(axis=0)


#part d)
less5  = np.where(np.any(5 > A,
axis = 1))

finaloutput = len(less5)

#part e)
less90  = np.where(np.any( 90 < A,
axis = 0))



#part f)
u, c = np.unique(A, return_counts=True)
dup = u[c > 2]



#part g)

sortedarr = np.sort(A, axis = 1) 

P = np.any(sortedarr[:,1:] == sortedarr[:,:-1], axis=1)
final = np.count_nonzero(P)


print('The Matrix: ')
print(A)


print('The min and max: ')
print(B)
print(C)

print('The average value of every even row: ')
print(Average)

print('The std: ')
print(std)


print('Numbers less than 5:')
print(finaloutput)

print('Numbers less than 90:')
print(len(less90))

print('Appear in matrix more than twice: ')
print(dup)

print('Number of rows contain duplicate values: ')
print(final)

The Matrix: 
[[51 73 83 63 17 13 26 59 51 35]
 [59 85 73 99 63 35 20  7 47 68]
 [41 51 87 74 41 36 64 75 60 32]
 [32 96 99 58 55 76  6 80 19 39]
 [40 36  9 40 23 37 46 24 29 56]
 [84 44 73 81 62 94 85  6 10 13]
 [13 61 37 77 75 12 55 44 77 82]
 [59 71 13  8 62 10  8 38 49  9]
 [89 33 57 63 49 12 18 86 55 48]
 [72  1 73  4 20 74 76 28 91 86]]
The min and max: 
1
99
The average value of every even row: 
[47.1 56.1 34.  53.3 51. ]
The std: 
[26.63625349 29.3259271  29.35114989 27.83181633 25.10298787]
Numbers less than 5:
1
Numbers less than 90:
1
Appear in matrix more than twice: 
[13 51 55 59 63 73]
Number of rows contain duplicate values: 
5


In [125]:
# PART 2

import numpy as np

def border(n,m):
    
    x = np.ones((n,m))
    x[1:-1, 1:-1] = 0
    print(x)

    
border(5,5)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [120]:
# PART 3

def closest(a, v):
    
    x = np.asarray(a)
    final = (np.abs(x - v)).argmin()
    return x[final]

a = [10, 3, 7, 8, 15]

closest(a, 4)

3

In [113]:
#PART 4 

def localMaxima(a):
    maxima = []
   
    for x in range(1, len(a)-1):
        if(a[x-1] < a[x] > a[x + 1]):
            maxima.append(a[x])

    if(len(maxima) > 0):
        print(maxima)
    else:
        print("No values")

a = [5, 8, 3, 1, 10, 9, 12]
 
localMaxima(a)



[8, 10]


In [123]:
#PART 5

A = np.array([[1, 2, 3, 4], [2,4,6,8], [1,3,5,7]])

norm = A/np.sum(A, axis=1).reshape(-1,1)

print(norm)



[[0.1    0.2    0.3    0.4   ]
 [0.1    0.2    0.3    0.4   ]
 [0.0625 0.1875 0.3125 0.4375]]
